### ISSUE TITLE
Extend the overpass query to fetch all public transit nodes

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/kamal#227]
The [query](https://github.com/hiposfer/kamal/blob/master/resources/overpass-api-query.txt) used to fetch OSM data for an area does not consider the public transport relations and therefore lacks enough data to process GTFS feeds produced with o2g. The query should be updated [similar to o2g](https://github.com/hiposfer/osmtogtfs/blob/master/demo/app.py#L117).

**Comment by mehdisadeghi** [comment]
Otherwise one would get errors like this:

```➜ lein run -m hiposfer.kamal.preprocessor resources/
2018-09-17 22:59:53.162:INFO::main: Logging initialized @7784ms
18-09-17 20:59:54 mpro.local INFO [hiposfer.kamal.preprocessor:55] - preprocessing OSM and GTFS files
processing area: FREIBURG
"Elapsed time: 23598.554514 msecs"
"Elapsed time: 181122.675479 msecs"
Exception in thread "main" clojure.lang.ExceptionInfo: stop didnt match to any known node in the OSM data #:stop{:id 2961990970, :location #hiposfer.kamal.network.core.Location{:lon 7.7178504, :lat 47.931048}, :name "Offnadingen B3"}, compiling:(/private/var/folders/kh/42ww8ghx1z30qbn3lnr7q6j4_0hblj/T/form-init2737463641660248429.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: stop didnt match to any known node in the OSM data {:stop/id 2961990970, :stop/location #hiposfer.kamal.network.core.Location{:lon 7.7178504, :lat 47.931048}, :stop/name "Offnadingen B3"}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at hiposfer.kamal.libs.fastq$link_stops$iter__9670__9674$fn__9675$fn__9676.invoke(fastq.clj:186)
	at hiposfer.kamal.libs.fastq$link_stops$iter__9670__9674$fn__9675.invoke(fastq.clj:182)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.lang.RT.nthFrom(RT.java:974)
	at clojure.lang.RT.nth(RT.java:933)
	at datascript.db$transact_tx_data.invoke(db.cljc:1026)
	at datascript.core$with.invoke(core.cljc:52)
	at datascript.core$with.invoke(core.cljc:47)
	at datascript.core$db_with.invoke(core.cljc:61)
	at hiposfer.kamal.preprocessor$prepare_data.invokeStatic(preprocessor.clj:43)
	at hiposfer.kamal.preprocessor$prepare_data.invoke(preprocessor.clj:35)
	at hiposfer.kamal.preprocessor$_main.invokeStatic(preprocessor.clj:61)
	at hiposfer.kamal.preprocessor$_main.invoke(preprocessor.clj:47)
	at clojure.lang.Var.invoke(Var.java:381)
	at user$eval3132.invokeStatic(form-init2737463641660248429.clj:1)
	at user$eval3132.invoke(form-init2737463641660248429.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
```

**Comment by carocad** [comment]
@mehdisadeghi I am not sure whether this is due to the overpass query. It would not make sense that there is a stop but not a pedestrian way nearby to match it.

I think that maybe the `nearest-search` algorithm that we are using is wrong and it might be causing the issue even though there is a close by node. We would have to investigate this though

**Comment by mehdisadeghi** [comment]
> It would not make sense that there is a stop but not a pedestrian way nearby to match it.

That's the problem. Some GTFS stops fall outside the search area and should be explicitly queried, otherwise overpass will only return nodes in the search area. In o2g I've used `(._; >;);` to fetch any linked node, regardless of their presence in the search area.

**Comment by carocad** [comment]
> o2g I've used (._; >;); to fetch any linked node, regardless of their presence in the search area.

Afaik, I'm already doing that. See snippet below. However the pedestrian ways are obviously not so long as public transport ones so they don't estrecht very far from the search area

```
// print ways
out body;
// find nodes of ways
>;
```

**Comment by mehdisadeghi** [comment]
> the pedestrian ways are obviously not so long as public transport ones

That could be the issue. I already tried adding relations and the processing went further until I got another missing node. I have to refine my query and then I'll put it on a PR for review.

**Comment by mehdisadeghi** [comment]
@carocad please see the [above commit](https://github.com/hiposfer/kamal/commit/8362a215dfbde0011c2e449d2fc33ee9e499fb75). I changed the query to include public transport nodes in the area. Without this change, necessary nodes were missing (which were present in the GTFS stops.txt btw). But we still get the exception even though the node is present. I have to still dig deeper.

**Comment by mehdisadeghi** [comment]
btw the new query dramatically increases the size of the OSM data so it should be optimized if possible.

**Comment by carocad** [comment]
> I changed the query to include public transport nodes in the area. Without this change, necessary nodes were missing (which were present in the GTFS stops.txt btw).

I don't think this is the way to go. If we would be taking about a gtfs feed from done random people, I think that we would inmediately state that the gtfs data must be contained inside the osm area. Any other assumption here would break the separation of concerns between osm and gtfs.

I think that we are trying to extend Kamal because this feed is coming from o2g which we also maintain so we just take for granted that those two should match each other.

I propose an alternative which I think covers the most general case (inspired by o2g overpass query).

Instead of relying on the name of the area to fetch in osm (Freiburg for example) provide a bounding box over which the current Kamal query would run. This way, we can expand the box as much as we need depending on the needs of the gtfs feed i.e no implicit dependency on predefined osm areas

What do you think?

**Comment by mehdisadeghi** [comment]
> the gtfs data must be contained inside the osm area. Any other assumption here would break the separation of concerns between osm and gtfs.

I understand your point and agree. However we are dealing with special case of inter-city routes, see below.

> Instead of relying on the name of the area to fetch in osm (Freiburg for example) provide a bounding box

I'm afraid that won't be so straight forward. The problem so far has been with relations that are stretched to nearby cities which are outside the area/bbox. Even with a bbox if we use OSM `recurse` functionality, it will bring in nodes that are outside the area/bbox. And of course Kamal will fail finding the nearest node to those stops since there isn't any.

I think our problem boils down to this question: how do we deal with inter-city routes? If they are common in GTFS feeds we have to find a solution. If they are rare we might very well crop the feeds or simply exclude them from the network.

**Comment by carocad** [comment]
> I'm afraid that won't be so straight forward. The problem so far has been with relations that are stretched to nearby cities which are outside the area/bbox

I see, it seems that I underestimated the problem. 

> I think our problem boils down to this question: how do we deal with inter-city routes? If they are common in GTFS feeds we have to find a solution. If they are rare we might very well crop the feeds or simply exclude them from the network.

Well, in the face of unknown information I prefer the simplest solution: crop them or exclude them from the network, whichever is easier for you in o2g.

Right now we are only familar with gtfs feeds from o2g so we dont have enough information to know what would be the best approach. I think that once we start using feeds provided by external sources, we will be able to start assesing the real dimension of the problem.

**Comment by carocad** [comment]
closing this as it was solved directly in o2g: https://github.com/hiposfer/osmtogtfs/pull/108
